name: flutter_secure_storage_linux
description: A dummy implementation to bypass GLib version issues on Linux.
version: 1.2.3
homepage: https://github.com/mogol/flutter_secure_storage

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface: ^1.1.2

flutter:
  # No plugin definition here!
